# This configuration configures ChirpStack Network Server for the EU868 band using a MQTT
# broker to communicate with the gateways. Many options and defaults have been
# omitted for simplicity.
#
# For other bands, see the ./examples/ sub-directory.
#
# See https://www.chirpstack.io/network-server/install/config/ for a full
# configuration example and documentation.
[general]
log_level=4

# PostgreSQL settings.
#
# Please note that PostgreSQL 9.5+ is required.
[postgresql]
dsn="postgres://chirpstack_ns:dbnspassword@localhost/chirpstack_ns?sslmode=disable"


# Redis settings
#
# Please note that Redis 2.6.0+ is required.
[redis]
# Redis url (e.g. redis://user:password@hostname/0)
url="redis://localhost:6379"


# Network-server settings.
[network_server]
# Network identifier (NetID, 3 bytes) encoded as HEX (e.g. 010203)
net_id="000000"


  # LoRaWAN regional band configuration.
  #
  # Note that you might want to consult the LoRaWAN Regional Parameters
  # specification for valid values that apply to your region.
  # See: https://www.lora-alliance.org/lorawan-for-developers
  [network_server.band]
  name="EU868"


  # LoRaWAN network related settings.
  [network_server.network_settings]

    # Extra channel configuration.
    #
    # Use this for LoRaWAN regions where it is possible to extend the by default
    # available channels with additional channels (e.g. the EU band).
    # The first 5 channels will be configured as part of the OTAA join-response
    # (using the CFList field).
    # The other channels (or channel / data-rate changes) will be (re)configured
    # using the NewChannelReq mac-command.
    #
    [[network_server.network_settings.extra_channels]]
    frequency=867100000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867300000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867500000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867700000
    min_dr=0
    max_dr=5

    [[network_server.network_settings.extra_channels]]
    frequency=867900000
    min_dr=0
    max_dr=5


    # Class B settings
    [network_server.network_settings.class_b]
    # Ping-slot data-rate.
    ping_slot_dr=0

    # Ping-slot frequency (Hz)
    #
    # Set this to 0 to use the default frequency plan for the configured region
    # (which could be frequency hopping).
    ping_slot_frequency=0


  # Network-server API
  #
  # This is the network-server API that is used by ChirpStack Application Server or other
  # custom components interacting with ChirpStack Network Server.
  [network_server.api]
  # ip:port to bind the api server
  bind="0.0.0.0:8000"

  # ca certificate used by the api server (optional)
  #ca_cert="/home/sandoche/certificates/certs/intermediate/intermediate.pem"
  ca_cert="/home/sandoche/certificates/certs/ca/ca.pem"

  # tls certificate used by the api server (optional)
  # tls_cert="/home/sandoche/certificates/certs/network-server/api/server/network-server-api-server.pem"
  tls_cert="/home/sandoche/certificates/certs/network-server/api/server/network-server-api-server-combined.pem"

  # tls key used by the api server (optional)
  tls_key="/home/sandoche/certificates/certs/network-server/api/server/network-server-api-server-key.pem"

  # Backend defines the gateway backend settings.
  #
  # The gateway backend handles the communication with the gateway(s) part of
  # the LoRaWAN network.
  [network_server.gateway.backend]
  # Backend
  type="mqtt"


    # MQTT gateway backend settings.
    #
    # This is the backend communicating with the LoRa gateways over a MQTT broker.
    [network_server.gateway.backend.mqtt]
    # MQTT topic templates for the different MQTT topics.
    #
    # The meaning of these topics are documented at:
    # https://www.chirpstack.io/gateway-bridge/
    #
    # The default values match the default expected configuration of the
    # ChirpStack Gateway Bridge MQTT backend. Therefore only change these values when
    # absolutely needed.

    # Event topic template.
    event_topic="gateway/+/event/+"

    # Command topic template.
    #
    # Use:
    #   * "{{ .GatewayID }}" as an substitution for the LoRa gateway ID
    #   * "{{ .CommandType }}" as an substitution for the command type
    command_topic_template="gateway/{{ .GatewayID }}/command/{{ .CommandType }}"

    # MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)
    server="tcp://localhost:1883"

    # Connect with the given username (optional)
    username=""

    # Connect with the given password (optional)
    password=""


# Metrics collection settings.
[metrics]
# Timezone
#
# The timezone is used for correctly aggregating the metrics (e.g. per hour,
# day or month).
# Example: "Europe/Amsterdam" or "Local" for the the system's local time zone.
timezone="Local"


# Join-server settings.

[join_server]

  # Settings  for DNS resolution
  resolve_join_eui=true
  resolve_domain_suffix=".joineui.iotreg.net"

  # The JoinEUI of the joinserver to  
  [[join_server.servers]]
  join_eui="0000000000000001"
  #ca_cert="/home/sandoche/certificates/certs/intermediate/intermediate.pem"
  ca_cert="/home/sandoche/certificates/certs/ca/ca.pem"
  tls_cert="/home/sandoche/certificates/certs/application-server/join-api/client/application-server-join-api-client-combined.pem"
  tls_key="/home/sandoche/certificates/certs/application-server/join-api/client/application-server-join-api-client-key.pem"




  # Default join-server settings.
  #
  # This join-server will be used when resolving the JoinEUI is set to false
  # or as a fallback when resolving the JoinEUI fails.
  [join_server.default]
  # hostname:port of the default join-server
  #
  # This API is provided by ChirpStack Application Server.
  server="https://51.91.79.176:443"
  # ca_cert="/home/sandoche/certificates/certs/intermediate/intermediate.pem"
  ca_cert="/home/sandoche/certificates/certs/ca/ca.pem"
  tls_cert="/home/sandoche/certificates/certs/application-server/join-api/client/application-server-join-api-client-combined.pem"
  tls_key="/home/sandoche/certificates/certs/application-server/join-api/client/application-server-join-api-client-key.pem"

[roaming]
resolve_netid_domain_suffix=".netid.iotreg.net"

[roaming.api]
bind="0.0.0.0:443"
#ca_cert="/home/sandoche/certificates/certs/intermediate/intermediate.pem"
ca_cert="/home/sandoche/certificates/certs/ca/ca.pem"
tls_cert="/home/sandoche/certificates/certs/network-server/roaming/000000/server/server-combined.pem"
tls_key="/home/sandoche/certificates/certs/network-server/roaming/000000/server/server-key.pem"
  # ca_cert="/home/brocaar/certs/ca/ca.pem"
  #  tls_cert="/home/brocaar/certs/chirpstack-network-server/roaming/000001/server/chirpstack-network-server-roaming-000001-server.pem"
  #  tls_key="/home/brocaar/certs/chirpstack-network-server/roaming/000001/server/chirpstack-network-server-roaming-000001-server-key.pem"

[roaming.default]
enabled=true
passive_roaming=true
passive_roaming_lifetime="24h"
# ca_cert="/home/sandoche/certificates/certs/intermediate/intermediate.pem"
ca_cert="/home/sandoche/certificates/certs/ca/ca.pem"
tls_cert="/home/sandoche/certificates/certs/network-server/roaming/000000/client/client-combined.pem"
tls_key="/home/sandoche/certificates/certs/network-server/roaming/000000/client/client-key.pem"
